In [2]:
import pandas as pd
import psycopg2

In [3]:
dataFrame_ExpertReviews = pd.read_excel(r"C:\Users\Jaume\Documents\MDDB\Database Management\ExpertReviewsClean43LIWC.xlsx")

In [4]:
dataFrame_UserReviews = pd.read_excel(r"C:\Users\Jaume\Documents\MDDB\Database Management\UserReviewsClean43LIWC.xlsx")

In [5]:
dataFrame_MetaClean = pd.read_excel(r"C:\Users\Jaume\Documents\MDDB\Database Management\metaClean43Brightspace.xlsx")

In [6]:
dataFrame_Sales = pd.read_excel(r"C:\Users\Jaume\Documents\MDDB\Database Management\sales.xlsx")

In [7]:
cleanDataFrame_Sales = pd.DataFrame()
cleanDataFrame_Sales = dataFrame_Sales.drop(columns=['domestic_box_office','international_box_office','Unnamed: 8', 'opening_weekend','theatre_count','avg run per theatre','creative_type'])


cleanDataFrame_Sales

,year,release_date,title,genre,worldwide_box_office,production_budget,runtime,keywords,url
0,2000,January 1st,Bakha Satang,Drama,76576.0,NaN,129.0,NaN,https://www.the-numbers.com/movie/Bakha-Satang...
1,2001,January 12th,Antitrust,Thriller/Suspense,17865209.0,30000000.0,NaN,NaN,https://www.the-numbers.com/movie/Antitrust
2,2000,January 28th,Santitos,NaN,NaN,NaN,105.0,NaN,https://www.the-numbers.com/movie/Santitos
3,2002,2002 (Wide) by,Frank McKlusky C.I.,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...
4,2002,January 25th,A Walk to Remember,Drama,46060861.0,11000000.0,NaN,Coming of Age,https://www.the-numbers.com/movie/Walk-to-Reme...
...,...,...,...,...,...,...,...,...,...
30607,2021,January 1st,Jokbeoldu sinmun iyagi,Documentary,12356.0,NaN,168.0,NaN,https://www.the-numbers.com/movie/Jokbeoldu-si...
30608,2021,March 5th,My Salinger Year,Drama,968849.0,NaN,101.0,Set in New York City,https://www.the-numbers.com/movie/My-Salinger-...
30609,2021,January 1st,Escort Vehicle 36,Action,240000.0,NaN,85.0,NaN,https://www.the-numbers.com/movie/Escort-Vehic...
30610,2021,May 21st,The Dry,Thriller/Suspense,17351923.0,NaN,118.0,Crime Thriller,https://www.the-numbers.com/movie/Dry-The-(Aus...
30611,2021,January 1st,Posledniy bogatyr. KorenÃ¢â‚¬â„¢ Zla,Adventure,33396899.0,NaN,NaN,NaN,https://www.the-numbers.com/movie/Posledniy-bo...

In [20]:
cleanDataFrame_UserReviews = dataFrame_UserReviews[['url','reviewer', 'Rev','idvscore']]

movieColumn = cleanDataFrame_UserReviews['url']
movieNames = []

for movie in movieColumn:
    movieName = movie.split('/')
    movieTemp = movieName[-1]
    movieNames.append(movieTemp)
    
cleanDataFrame_UserReviews['movies'] = movieNames

C:\Users\Jaume\AppData\Local\Temp\ipykernel_11192\512833260.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleanDataFrame_UserReviews['movies'] = movieNames

In [23]:
cleanDataFrame_ExpertReviews = dataFrame_ExpertReviews[['url','reviewer', 'Rev','idvscore']]

movieColumn = cleanDataFrame_ExpertReviews['url']
movieNames = []

for movie in movieColumn:
    movieName = movie.split('/')
    movieTemp = movieName[-1]
    movieNames.append(movieTemp)
    
cleanDataFrame_ExpertReviews['movies'] = movieNames

C:\Users\Jaume\AppData\Local\Temp\ipykernel_11192\3033254557.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleanDataFrame_ExpertReviews['movies'] = movieNames

In [9]:
cleanDataFrame_ExpertReviews = dataFrame_ExpertReviews[['url','reviewer', 'Rev']]
cleanDataFrame_ExpertReviews

#Now we add the two clean review tables and we make it one
frames = [cleanDataFrame_UserReviews,cleanDataFrame_ExpertReviews]
clean_ReviewsTable = pd.concat(frames)

clean_ReviewsTable

,url,reviewer,Rev,idvscore
0,https://www.metacritic.com/movie/bronson,'Longbottom94','Many have dismissed this film for not explor...,8
1,https://www.metacritic.com/movie/bronson,'MartinB','Anyone who doesn t like this movie simply ju...,9
2,https://www.metacritic.com/movie/bronson,'Jaakko','Not sure what to think at this film at first...,10
3,https://www.metacritic.com/movie/bronson,'CapoR','Nicely portrayed but it lacks the elements t...,6
4,https://www.metacritic.com/movie/bronson,'OrwellB.','Bronson is more than entertainment. It is ar...,8
...,...,...,...,...
238968,https://www.metacritic.com/movie/spirited-away,'Desson Thomson','This movie -- which is equally appealing to ...,NaN
238969,https://www.metacritic.com/movie/spirited-away,'David Sterritt',"'Too intense for the youngest viewers, but te...",NaN
238970,https://www.metacritic.com/movie/spirited-away,'Wesley Morris','Delivers chunks of Yellow Submarine and The ...,NaN
238971,https://www.metacritic.com/movie/spirited-away,'William Arnold','Has the power to transport us to a different...,NaN
238972,https://www.metacritic.com/movie/spirited-away,'C.W. Nevius',"'A lovely, evocative tour de force. So why do...",NaN

In [11]:
#we try to connect to postgresql
import psycopg2

# Database connection parameters
db_params = {
    'host': 'localhost',
    'port': '5433',
    'database': 'Movie Database',
    'user': 'postgres',
    'password': 'Reves360'
}


# Establish a connection to the PostgreSQL server
connection = psycopg2.connect(**db_params)

# Create a cursor object to interact with the database
cursor = connection.cursor()

# Execute SQL queries or commands here
print("We would input the queries here")
# Commit any changes to the database (if applicable)
# connection.commit()

# Close the cursor and connection
cursor.close()
connection.close()

print("Connection Done")

We would input the queries here
Connection Done